project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views


app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    
    path('update-item/', views.update_item, name='update-item'),
    path('process-order/', views.process_order, name='process-order'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                null=True)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200, null=True)
    
    def __str__(self):
        return self.name
    
class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    score = models.PositiveIntegerField(null=True, default=0)
    image = models.ImageField(upload_to='covers', null=True, blank=True)
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        
        return url
    
    def __str__(self):
        return self.name
    
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True)
    transaction_id = models.CharField(max_length=200, null=True)
    shipping = models.PositiveIntegerField(default=0)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    
    def __str__(self):
        return f'Order: {self.id}'
    
    @property
    def get_quantity(self):
        orderitems = self.orderitem_set.all()
        if orderitems:
            quantity = orderitems.count()
        else:
            quantity = 0
        
        return quantity
    
    @property
    def get_cart_subtotal(self):
        orderitems = self.orderitem_set.all()
        if orderitems:
            total = sum([item.get_price for item in orderitems])
        else:
            total = 0
            
        return total
    
    @property
    def get_shipping(self):
        orderitems = self.orderitem_set.all()
        if orderitems:
            total_cart = sum([item.get_price for item in orderitems])
            if total_cart >= 250:
                total = 0
            else:
                total = sum([10 for item in orderitems])
        else:
            total = 0
            
        return total
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        if orderitems:
            shipping = sum([item.get_price for item in orderitems])
            if shipping >= 250:
                shipping = 0
            else:
                shipping = sum([10 for item in orderitems])
        
            subtotal = sum([item.get_price for item in orderitems])
            total = shipping + subtotal
        else:
            total = 0
            
        return total
    
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'OrderItem: {self.id}, product: {self.product}, order: {self.order}'
    
    @property
    def get_price(self):
        return self.product.price
    
class Transaction(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'Transaction: {self.id}'

store/views.py
import datetime
import json

from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from .models import *

# Create your views here.
def home(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer,
                                                     complete=False)
        items = order.orderitem_set.all()
        cart_items = order.get_quantity
    else:
        items = []
        order = {
            'get_quantity': 0,
            'get_shipping': 0,
            'get_cart_subtotal': 0,
            'get_cart_total': 0
        }
        cart_items = order['get_quantity']
    
    
    products = Product.objects.all()
    context = {
        'products': products,
        'cart_items': cart_items
    }
    return render(request, 'store/home.html', context)


def cart(request):
    
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer,
                                                     complete=False)
        items = order.orderitem_set.all()
        cart_items = order.get_quantity
    else:
        items = []
        order = {
            'get_quantity': 0,
            'get_shipping': 0,
            'get_cart_subtotal': 0,
            'get_cart_total': 0
        }
    context = {
        'items': items,
        'order': order,
        'cart_items': cart_items
    }
    return render(request, 'store/cart.html', context)


def checkout(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer,
                                                     complete=False)
        items = order.orderitem_set.all()
        cart_items = order.get_quantity
    else:
        items = []
        order = {
            'get_quantity': 0,
            'get_shipping': 0,
            'get_cart_subtotal': 0,
            'get_cart_total': 0
        }
        
    context = {
        'items': items,
        'order': order,
        'cart_items': cart_items
    }
    return render(request, 'store/checkout.html', context)

@csrf_exempt
def update_item(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action:', action)
    print('Product:', productId)
    
    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer,
                                                 complete=False)
    
    orderItem, created = OrderItem.objects.get_or_create(order=order,
                                                         product=product)
    
    if action == 'remove':
        orderItem.delete()
    
    return JsonResponse('Item was added', safe=False)

def process_order(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    
    if request.user.is_authenticated():
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer,
                                                    complete=False)
        total = data['form']['total']
        order.transaction_id = transaction_id
        
        if total == order.get_cart_total:
            order.complete = True
        
        order.save()
        
    else:
        print('User is not logged in')
        
    return JsonResponse('Payment submited', safe=False)

store/templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="box-element mb-4">
            <a class="btn btn-outline-secondary" href="{% url 'store:home' %}">&#x2190; Continue Shopping</a>

            <table class="table mt-4">
                <tr>
                    <th><h5>Items: <strong>{{ order.get_quantity }}</strong></h5></th>
                    <th><h5>Frete: <strong>R$ {{ order.get_shipping }}</strong></h5></th>
                    <th><h5>Subtotal: <strong>R$ {{ order.get_cart_subtotal }}</strong></h5></th>
                    <th><h4>Total: <strong>R$ {{ order.get_cart_total }}</strong></h4></th>
                    <th>
                        <a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'store:checkout' %}">Checkout</a>
                    </th>
                </tr>
            </table>
        </div><!--box element-->

        <div class="box-element">
            <div class="cart-row">
                <div style="flex:1"></div>
                <div style="flex:1"><strong>Item</strong></div>
                <div style="flex:1"><strong>Price</strong></div>
                <div style="flex:1"><strong></strong></div>
            </div>
            
            {% for item in items %}
            <div class="cart-row">
                <div style="flex:1">
                    <img class="row-image" src="{{ item.product.imageURL }}">
                </div>
                <div style="flex:2"><p>{{ item.product.name }}</p></div>
                <div style="flex:1"><p>R$ {{ item.product.price }}</p></div>
                <div style="flex:1">
                    <button data-product="{{ item.product.id }}" data-action="remove" class="btn btn-outline-danger btn-sm update-cart">Remove</button>
                </div>
            </div>
            {% empty %}
            <div class="cart-row">
                <p>Nenhum produto no carrinho.</p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

store/templates/store/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
	<div class="col-lg-6">
		<div class="box-element mb-4" id="form-wrapper">
            <form id="form">
                <div id="user-info">
                    <div class="form-field">
                        <input required class="form-control" type="text" name="name" placeholder="Name..">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="email" name="email" placeholder="Email..">
                    </div>
                </div>
                
                <hr>
                <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
            </form>
		</div>
		
        <div class="box-element hidden" id="payment-info">
            <small>Paypal Options</small>
            <button id="make-payment">Make Payment</button>
        </div>
	</div>

	<div class="col-lg-6">
		<div class="box-element">
            <div class="box-element">
                <a  class="btn btn-outline-secondary" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
                <hr>
                <h3>Order Summary</h3>
                <hr>
                {% for item in items %}
                <div class="cart-row">
                    <div style="flex:1">
                        <img class="row-image" src="{{ item.product.imageURL }}">
                    </div>
                    <div style="flex:2"><p>{{ item.product.name }}</p></div>
                    <div style="flex:1"><p>R$ {{ item.get_price }}</p></div>
                </div>
                {% empty %}
                    <p>Nenhum produto adicionado.</p>
                {% endfor %}
                <h5>Items:   {{ order.get_quantity }}</h5>
                <h5>Frete:   {{ order.get_shipping }}</h5>
                <h5>Subtotal:   R$ {{ order.get_cart_subtotal }}</h5>
                <hr>
                <h4>Total:   R$ {{ order.get_cart_total }}</h4>
            </div>
		</div>
	</div>
</div>

<script>
    
    var total = '{{ order.get_cart_total }}'

    if (user != 'AnonymousUser') {
        document.getElementById('form-wrapper').classList.add("hidden");
        document.getElementById('payment-info').classList.remove("hidden");
    }

    var form = document.getElementById('form')

    form.addEventListener('submit', function(e) {
        e.preventDefault()
        console.log('Form submited')
        document.getElementById('form-button').classList.add('hidden')
        document.getElementById('payment-info').classList.remove('hidden')
    })

    document.getElementById('make-payment').addEventListener('click', function(e) {
        submitFormData()
    })

    function submitFormData() {
        var userFormData = {
            'name': null,
            'email': null,
            'total': total,
        }

        if (user == 'AnonymousUser') {
            userFormData.name = form.name.value
            userFormData.email = form.email.value
        }

        var url = '/process-order/'

        fetch(url, {
            method:'POST',
            headers:{
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken,
            }, 
            body: JSON.stringify({'form': userFormData}),    
        })

        .then((response) => { response.json() })

        .then((data) => {
            console.log('Success:', data);
            alert('Transaction completed');  

            window.location.href = "{% url 'store:home' %}"

            })
    }
</script>

{% endblock content %}

store/templates/store/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
    {% for product in products %}
    <div class="col-lg-4">
        {% if product.image == '' %}
        <img class="thumbnail" src="{% static 'images/placeholder.png' %}" alt="thumbnail">
        {% else %}
        <div class="text-center game-box">
            <img src="{{ product.image.url }}" alt="thumbnail">
        </div>
        {% endif %}
        <div class="box-element product">
            <h3 class="game-title">
                <strong>{{ product.name }}</strong> <span class="badge bg-success">{{ product.score }}</span>
            </h3>
            <hr>
            <button data-product="{{product.id}}" data-action="add" class="btn btn-outline-primary add-btn update-cart">Add to Cart</button>
            <p class="product-price">R$ {{ product.price }}</p>
        </div>
    </div>
    {% empty %}
        <h3 class='mt-4 text-center'>Nenhum produto cadastrado</h3>
    {% endfor %}

</div>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <!-- links -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <script>
        var user = '{{ request.user }}'

        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');
    </script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'store:home' %}">Ecommerce</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'store:home' %}">Home</a>
                    </li>
                </ul>
                <div class="form-inline my-2 my-lg-0">
                    <a href="#"class="btn btn-warning">Login</a>
                    
                    <a href="{% url 'store:cart' %}">
                       <img  id="cart-icon" src="{% static 'images/cart-icon.svg' %}">
                       <p id="cart-total">{{ cart_items }}</p>
                   </a>
               </div>               
            </div>
        </div>
        </nav>

    <div class="container">
        {% block content %}{% endblock content %}
    </div>

    <!-- scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <script src="{% static 'js/cart.js' %}"></script>
</body>
</html>